### ISSUE TITLE
Anti-paywall: Washington Post Crossword

### ISSUE THREAD

**Issue by joshtch** [liamengland1/miscfilters#30]
https://www.washingtonpost.com/crossword-puzzles/daily/

Spent over an hour trying to figure out why my ad blocker was preventing me from playing the crossword at WaPo. Turns out it was the Anti-paywall blocklist in this repo.

I just now narrowed it down to this line in the blocklist:

    washingtonpost.com##+js(set, $.prototype.wpPreroll, noopFunc)

With this line disabled, the crosswords work as expected.

Separate from, but related to, the above: on https://games.washingtonpost.com/ the following line breaks their (HTML5?) games.

    ||d2p9l91d5g68ru.cloudfront.net/PrerollPlugin/

I have disabled both lines without any apparent problems with paywall messages but that could be due to other blocker directives I have active.

I'm not very familiar with the Ad Blocker syntax. Can we add exceptions to these rules so they do not apply at `washingtonpost.com/crossword-puzzles/*` and `games.washingtonpost.com/games/*`, respectively? Thanks!

**Comment by llacb47** [comment]
sorry, I've been busy. Thank you for your work on this issue, I will review this soon :)

**Comment by liamengland1** [comment]
fixed, i hope. apologies for the extremely long delay. I couldn't reproduce the games being broken, but the crosswords were still broken by the `##+js()` rule, so I removed it

**Comment by joshtch** [comment]
No problem, thanks for finally getting around to it. 

Looks like it's working! Thanks, man!
