### ISSUE TITLE
ba.no

### ISSUE THREAD

**Issue by DandelionSprout** [liamengland1/miscfilters#31]
Fully bypassable paywall at `https://www.ba.no/bas-koronastudio/s/5-8-1689687?p=lc-3019925-7071-bergensavisen`. I propose for Anti-Paywall Filters:
```
ba.no##html:has(div[class*=livecenter]) amedia-include[src*="/incentive/"]:style(border: 10px !important; border-color: #CD5C5C !important; border-style: solid !important)
ba.no##html:has(div[class*=livecenter]) .aid-background-blur:style(filter: none !important)
ba.no##html:has(div[class*=livecenter]) #aid-overlay:style(background: none !important; height: 0px !important; min-height: unset !important)
ba.no##html:has(div[class*=livecenter]) amedia-incentive
```

![image](https://user-images.githubusercontent.com/22780683/143731941-669f7190-6c31-4281-a352-580863bba08a.png)

Only tested on desktop browsers at the time of writing. `html:has(div[class*=livecenter])` is neccessary to avoid conflicts with paywalls on regular articles, where they are *not* fully bypassable.

Despite `Amedia` owning more than 80 newssites in Norway, `BA.no` was the only one I could find with ease that had paywalls on newsfeeds.

**Comment by liamengland1** [comment]
Yeah, it's still me. Check the slack for confirmation lol. Appreciate the kind words :)
