### ISSUE TITLE
bloomberg.com (mobile) antipaywall

### ISSUE THREAD

**Issue by bradenglund** [liamengland1/miscfilters#37]
I am using the [antipaywall.txt](https://github.com/llacb47/miscfilters/blob/8b275b1469b2606b67942df0dbeb40e997701df8/antipaywall.txt) filter on mobile and experiencing an error loading the full page for articles from bloomberg.com.

https://www.bloomberg.com/news/articles/2021-12-22/omicron-at-least-doubles-risk-of-getting-infected-on-a-plane
![bloomberg](https://user-images.githubusercontent.com/28195153/147116167-03386720-86c4-4376-8749-2daa5441f472.jpg)

The filter for bloomberg shows these three entries, which I have manually added as custom user rules.
https://github.com/llacb47/miscfilters/blob/8b275b1469b2606b67942df0dbeb40e997701df8/antipaywall.txt#L76-L79

After disabling the filter in subscriptions, through trial and error, I have identified the rule which seems to be causing a problem.
![Attachment0](https://user-images.githubusercontent.com/28195153/147115775-0d6022bb-bb7c-498a-b76a-134ab277b691.jpeg)

Device specs:
Mobile Safari
iPhone v15.2
Adguard v4.3.0(911)

**Comment by liamengland1** [comment]
Should be fixed for desktop now, however the fix won't work on mobile browsers
