### ISSUE TITLE
Quora paywall

### ISSUE THREAD

**Issue by andreewmat** [liamengland1/miscfilters#39]
Link: `https://www.quora.com/What-are-some-of-the-greatest-tennis-matches-ever-played?share=1`

Suggested filter: 
`quora.com##.qu-overflowY--hidden:style(-webkit-mask-image: none !important)`
`quora.com##div[style*=".paywall_blur."]`
`quora.com##.qu-zIndex--qtext_overlay`

**Comment by liamengland1** [comment]
fixed, sorry for the delay
