### ISSUE TITLE
studocu.com

### ISSUE THREAD

**Issue by DandelionSprout** [liamengland1/miscfilters#40]
Page blurring and Premium prompt on `https://www.studocu.com/no/document/universitetet-i-bergen/norsk-hovedmal/nor1212-nor1232-norsk-sidemal-v2021/17623890`. I propose:
```
studocu.com##.page-content:style(filter: none !important; user-select: unset !important)
studocu.com##div[role=presentation] + div:last-of-type
studocu.com##.page-content[style*=filter] + div[class]
```
![image](https://user-images.githubusercontent.com/22780683/150736276-112843f3-f2b8-4424-a998-49287e495141.png)
* Adblockers: uBO 1.40.9b2 + IDCAC 3.3.5
* Browser: Chrome 97.0.4692.99 x64
* OS: Windows 11 x64
* Lists in use: 
![image](https://user-images.githubusercontent.com/22780683/150736403-ac4a1f26-47bc-4f71-9084-04e8ec14a562.png)

**Comment by liamengland1** [comment]
fixed, sorry for the delay
