### ISSUE TITLE
WSJ doesn't unblock

### ISSUE THREAD

**Issue by WoodpeckerBaby** [liamengland1/miscfilters#44]
Example: https://www.wsj.com/articles/stocks-are-divorced-from-the-economybut-wont-be-forever-11660999586 

I hope WSJ can be supported.

**Comment by liamengland1** [comment]
Unfortunately it can't be supported in a filterlist, due to requiring URL redirects which is not possible.

You can try my userscript https://gist.github.com/liamengland1/b3f233f59871e741dac3dd6d2c9125d3
