### ISSUE TITLE
theglobeandmail.com

### ISSUE THREAD

**Issue by WoodpeckerBaby** [liamengland1/miscfilters#45]
https://www.theglobeandmail.com/business/article-uber-ufcw-union-gig-workers/

Doesn't unblock paywall.

**Comment by AntiAdvert** [comment]
https://web.archive.org/web/20220826121457/https://www.theglobeandmail.com/business/article-uber-ufcw-union-gig-workers/

**Comment by liamengland1** [comment]
fixed, sorry for the delay
