### ISSUE TITLE
Certain invidious instances may be blocked by "discontinued/anti-serviceworker"

### ISSUE THREAD

**Issue by FuccDucc** [liamengland1/miscfilters#49]
Please make an exception to the discontinuation of the [anti-serviceworker](https://raw.githubusercontent.com/llacb47/miscfilters/master/discontinued/anti-serviceworker.txt) list by whitelisting any page with requests that identify it as Invidious instances, as it currently breaks video playback in the case of certain Invidious instance providers. Example case written out at [https://github.com/Sommerwiesel/invidious/issues/5](https://github.com/Sommerwiesel/invidious/issues/5) where the repro video link on their site was [https://invidious.nerdvpn.de/watch?v=-lz30by8-sU](https://invidious.nerdvpn.de/watch?v=-lz30by8-sU)

I know it's seen as discontinued, but so far it hasn't caused major issues in daily web browsing, while it is believed by many users to benefit security and privacy due to its generic anti-serviceworker functions. So fixing the minor issue here and there can be the way to go, and worth it in my opinion.

**Comment by liamengland1** [comment]
Fixed, thanks! Glad to hear the list is beneficial to you
