### ISSUE TITLE
new name ... new URL?

### ISSUE THREAD

**Issue by AntiAdvert** [liamengland1/miscfilters#52]
or did you quit maining the list? `https://filterlists.com/lists/anti-paywall-filters`

**Comment by AntiAdvert** [comment]
oh, I found out there is some sort of redirection. anyhow, @liamengland1 could you give an answer for the second question?

**Comment by liamengland1** [comment]
Yeah, I changed my GH username. GH will redirect the old urls so they don't break. I am still maintaining this list, but I am in college now and have less time to devote to open-source at the moment.

**Comment by AntiAdvert** [comment]
Thanks for the response, understandable.. But did you consider giving someone trustworthy writing permissions?
