### ISSUE TITLE
New Nytimes script to block 

### ISSUE THREAD

**Issue by weirdal3333** [liamengland1/miscfilters#55]
You might want to use a wildcard instead of v2 in case they ever update the script to v3 or something
This script edits the page to just be a title, picture, and the "log in and pay us" popup.
`https://samizdat-graphql.nytimes.com/graphql/v2`

Here's the persistent  'log in to pay us' box:
`###gateway-content`

The lines to add to the ublock list are:
```
||samizdat-graphql.nytimes.com/graphql/*
nytimes.com###gateway-content
```
The wildcard there is futureproofing if the script gets updated for a different name or if they add more scripts. It doesn't block anything else.

**Comment by liamengland1** [comment]
should be fixed ^ let me know if it works or doesn't work for you
