### ISSUE TITLE
elmercurio.com is not working

### ISSUE THREAD

**Issue by dragonxtek** [liamengland1/miscfilters#56]
I applied the filter "||merreader.emol.cl/assets/js/merPramV2.js$script,domain=elmercurio.com" in uBlock, but the paywall still appears
![Selection_431](https://user-images.githubusercontent.com/10552658/234979761-40940c47-c764-4b5d-ac08-01e027a9f131.jpg)

**Comment by weirdal3333** [comment]
This works instead:
`||digital.elmercurio.com/assets/js/merPramV2.js`

They must have changed the site structure

**Comment by dragonxtek** [comment]
Unfortunately the content of the site does not load due to a 403 error, so the content cannot be accessed.
![Selection_464](https://user-images.githubusercontent.com/10552658/236313379-e70fc46f-00b5-48ec-af73-b6d321070ecd.jpg)
Thanks anyway
