### ISSUE TITLE
https://www.bizjournals.com script

### ISSUE THREAD

**Issue by weirdal3333** [liamengland1/miscfilters#57]
https://cdn.cxense.com/cx.cce.js

This script deletes the article elements from the page and pops up the paywall if it detects you aren't logged in/subscribed, potentially on more than just the business journal site.

An exception is specifically in easylist for this script for some reason.
The line to add to ublock origin to force it to block the script is:
`||cdn.cxense.com/cx.cce.js$important`

**Comment by liamengland1** [comment]
I fixed it with a scriptlet since the exception in easylist is due to the script being necessary for article recommendations. thanks for reporting!
