### ISSUE TITLE
request adding www.hindutamil.in to the filter list

### ISSUE THREAD

**Issue by WeAreLegion999** [liamengland1/miscfilters#58]
pls consider adding www.hindutamil.in to the filter list
example article behind paywall https://www.hindutamil.in/news/opinion/columns/1017266-the-life-and-art-of-marginalized-people.html
thanks in advance!

**Comment by liamengland1** [comment]
server-side paywall, cannot be fixed in this list afaik. possibly bypassed with user agent spoofing but I didn't test
