### ISSUE TITLE
request update to ft.com filters

### ISSUE THREAD

**Issue by WeAreLegion999** [liamengland1/miscfilters#59]
Financial Times is still being paywalled despite the entries on the list. 

! Financial Times AMP site (amp.ft.com)
amp.ft.com##.amp-access-barrier
amp.ft.com##+js(ra, subscriptions-section, [subscriptions-section="content"])
||amp-access-svc.memb.ft.com/amp-pingback
amp.ft.com##.n-content-layout:has(.n-content-heading-4:has-text(newsletter))

Update would be appreciated. Thank you!

**Comment by liamengland1** [comment]
AMP (previous fix included) is dead. You can read FT articles by setting referer to google or twitter (t.co). That cannot be done with this list.
