### ISSUE TITLE
dailymail paywall no longer blocked

### ISSUE THREAD

**Issue by MadMaxMangos** [liamengland1/miscfilters#67]
Hi, can you update this to block the paywall on dailymail.co.uk again as its stopped working for that. thanks

**Comment by liamengland1** [comment]
Couldn't get it to show up for me but I've added it now

https://github.com/liamengland1/miscfilters/commit/06b099ec08fb7250f3d17e90f6b3b68f14244c99

**Comment by liamengland1** [comment]
https://github.com/liamengland1/miscfilters/commit/b5a69a86eb07a3e70ce30ae99c18e44440f5ecec
