### ISSUE TITLE
paywall not being filtered

### ISSUE THREAD

**Issue by MELERIX** [liamengland1/miscfilters#71]
here: https://www.latercera.com/la-tercera-pm/noticia/he-llegado-al-limite-de-la-contradiccion-entre-el-personaje-y-la-persona-inigo-errejon-y-el-adios-a-la-vida-politica-de-otra-figura-de-podemos/TPFXOCIG2NHNHO5WHI426N6Q6I/

**Comment by liamengland1** [comment]
Fixed
