### ISSUE TITLE
anti-paywall list trips the Houston Chronicle, white screen

### ISSUE THREAD

**Issue by JL2210** [liamengland1/miscfilters#72]
This was the link I was attempting to view: https://www.houstonchronicle.com/news/houston-texas/health/article/abortion-death-obgyns-letter-abbott-19886456.php

With the list active a blank screen is shown.

With the list off or adding another rule (see below) the page loads correctly.

The rule that seems to fix it (thanks @Procyon-b):

```
houstonchronicle.com#@#[data-block-type="ad"]:upward(1)
```

I noticed something similar already in the list
```
[lots of stuff]##[data-block-type="ad"]:upward(1)
```

not sure what the difference between `##` and `#@#` is, haven't messed with easylist stuff yet

**Comment by liamengland1** [comment]
Thanks
